package dev.buildopt.patcher;

import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;

/** Exact recipe that opts a root Gradle build into the local build cache. */
public final class GradleBuildCachePropertiesRecipe {
    public static final String RECIPE_ID = "GRADLE_BUILD_CACHE_PROPERTIES_V1";
    public static final String RECIPE_VERSION = "1.0";
    private static final int MAXIMUM_POSTIMAGE_BYTES = 1024 * 1024;
    private static final String MARKER = "# BuildOpt GRADLE_BUILD_CACHE_PROPERTIES_V1\n";
    private static final String PROPERTY = "org.gradle.caching=true\n";
    private static final String SUFFIX = "\n" + MARKER + PROPERTY;
    private static final int MAXIMUM_SOURCE_BYTES =
            MAXIMUM_POSTIMAGE_BYTES - SUFFIX.getBytes(StandardCharsets.UTF_8).length;

    private GradleBuildCachePropertiesRecipe() {
    }

    /** Produces one exact full-file replacement for an existing root gradle.properties. */
    public static Result apply(String relativePath, byte[] source) throws PatchFailure {
        if (!"gradle.properties".equals(relativePath)
                || source == null
                || source.length == 0
                || source.length > MAXIMUM_POSTIMAGE_BYTES) {
            reject("build-cache recipe requires a bounded root gradle.properties");
        }
        byte[] input = source.clone();
        String text = decode(input);
        if (text.indexOf('\0') >= 0
                || text.indexOf('\r') >= 0
                || !text.endsWith("\n")) {
            reject("build-cache recipe requires NUL-free LF source ending in a newline");
        }
        if (isGeneratedOutput(text)) {
            return result(input, input, false);
        }
        if (source.length > MAXIMUM_SOURCE_BYTES) {
            reject("build-cache recipe source exceeds the bounded input limit");
        }
        if (text.contains("org.gradle.caching") || text.contains(MARKER.trim())) {
            reject("build-cache recipe found an existing or ambiguous property");
        }
        return result(
                input,
                (text + SUFFIX).getBytes(StandardCharsets.UTF_8),
                true);
    }

    private static boolean isGeneratedOutput(String text) {
        if (!text.endsWith(SUFFIX) || text.length() <= SUFFIX.length()) {
            return false;
        }
        String original = text.substring(0, text.length() - SUFFIX.length());
        return original.endsWith("\n")
                && !original.contains("org.gradle.caching")
                && !original.contains(MARKER.trim());
    }

    private static String decode(byte[] source) throws PatchFailure {
        try {
            return StandardCharsets.UTF_8.newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(source))
                    .toString();
        } catch (CharacterCodingException exception) {
            throw new PatchFailure(
                    PatchFailure.Status.PROPOSED,
                    "build-cache recipe source is not UTF-8",
                    exception);
        }
    }

    private static Result result(byte[] preimage, byte[] postimage, boolean changed)
            throws PatchFailure {
        try {
            return new Result(
                    changed,
                    PatchBundleVerifier.digestBytes(preimage),
                    PatchBundleVerifier.digestBytes(postimage),
                    postimage);
        } catch (GeneralSecurityException exception) {
            throw new PatchFailure(
                    PatchFailure.Status.PROPOSED,
                    "build-cache recipe cannot calculate content digests",
                    exception);
        }
    }

    private static void reject(String message) throws PatchFailure {
        throw new PatchFailure(PatchFailure.Status.PROPOSED, message);
    }

    /** Immutable exact replacement generated by this recipe version. */
    public static final class Result {
        private final boolean changed;
        private final String preimageDigest;
        private final String postimageDigest;
        private final byte[] postimage;

        private Result(
                boolean changed,
                String preimageDigest,
                String postimageDigest,
                byte[] postimage) {
            this.changed = changed;
            this.preimageDigest = preimageDigest;
            this.postimageDigest = postimageDigest;
            this.postimage = postimage.clone();
        }

        public boolean changed() { return changed; }
        public String preimageDigest() { return preimageDigest; }
        public String postimageDigest() { return postimageDigest; }
        public byte[] postimage() { return postimage.clone(); }
    }
}
