package stickywrapper

import (
	"bytes"
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"
)

type fakeResolver struct {
	latest       Release
	versions     map[string]Release
	latestCalls  int
	versionCalls int
	err          error
}

func (resolver *fakeResolver) Latest(context.Context) (Release, error) {
	resolver.latestCalls++
	if resolver.err != nil {
		return Release{}, resolver.err
	}
	return resolver.latest, nil
}

func (resolver *fakeResolver) Version(_ context.Context, version string) (Release, error) {
	resolver.versionCalls++
	if resolver.err != nil {
		return Release{}, resolver.err
	}
	release, ok := resolver.versions[version]
	if !ok {
		return Release{}, errors.New("release not found")
	}
	return release, nil
}

func fixtureRelease(version string, seed byte) Release {
	digest := strings.Repeat(string(seed), 64)
	return Release{
		Version: version,
		Distributions: map[string]Distribution{
			"linux-amd64": {
				URL:    fmt.Sprintf("https://downloads.example.invalid/v%s/buildopt-%s-linux-amd64.tar.gz", version, version),
				SHA256: digest,
			},
			"macos-amd64": {
				URL:    fmt.Sprintf("https://downloads.example.invalid/v%s/buildopt-%s-darwin-amd64.tar.gz", version, version),
				SHA256: digest,
			},
			"macos-arm64": {
				URL:    fmt.Sprintf("https://downloads.example.invalid/v%s/buildopt-%s-darwin-arm64.tar.gz", version, version),
				SHA256: digest,
			},
			"windows-amd64": {
				URL:    fmt.Sprintf("https://downloads.example.invalid/v%s/buildopt-%s-windows-amd64.zip", version, version),
				SHA256: digest,
			},
		},
	}
}

func configuredFixture() Config {
	return Config{
		Mode: "auto", ServerURL: "https://buildopt.example.invalid",
		ProjectScope: "example/pilot", CredentialEnv: "BUILDOPT_TOKEN",
		TrialBudgetPercent: 5,
	}
}

func TestCanonicalReleaseMatchesCommittedContractFixture(t *testing.T) {
	release := Release{
		Version: "0.6.1",
		Distributions: map[string]Distribution{
			"linux-amd64": {
				URL: "https://github.com/tonyredondo/buildopt/releases/download/v0.6.1/buildopt-0.6.1-linux-amd64.tar.gz",
				SHA256: "a543acda9ec47914f25f1b4994e9337aae5873fa89d32bedb807d078357307f9",
			},
			"macos-amd64": {
				URL: "https://github.com/tonyredondo/buildopt/releases/download/v0.6.1/buildopt-0.6.1-darwin-amd64.tar.gz",
				SHA256: "ea1107eedcd6ca5731964b8d4b3a69541dd85637fde5e2bd2e0216d3a75ace2e",
			},
			"macos-arm64": {
				URL: "https://github.com/tonyredondo/buildopt/releases/download/v0.6.1/buildopt-0.6.1-darwin-arm64.tar.gz",
				SHA256: "866a804d876ef26df1ec9237017578f88d01bde6800f863454d8689166e25001",
			},
			"windows-amd64": {
				URL: "https://github.com/tonyredondo/buildopt/releases/download/v0.6.1/buildopt-0.6.1-windows-amd64.zip",
				SHA256: "8338745bd49453cea3bf27a24c0b4620202086bc4fdeafdb6f0efb404039106a",
			},
		},
	}
	config := Config{
		Mode: "auto", ServerURL: "https://buildopt.example.invalid",
		ProjectScope: "example/buildopt-pilot", CredentialEnv: "BUILDOPT_TOKEN",
		TrialBudgetPercent: 5,
	}
	snapshot := canonicalSnapshot(release, config)
	fixtureRoot := filepath.Join("..", "..", "fixtures", "sticky-wrapper-contract", "valid")
	for _, relative := range targetPaths {
		fixture := mustRead(t, filepath.Join(fixtureRoot, filepath.FromSlash(relative)))
		if !bytes.Equal(snapshot.Files[relative], fixture) {
			t.Fatalf("generated %s differs from the committed contract fixture", relative)
		}
	}
}

func TestInitIsDeterministicAndCheckIsReadOnly(t *testing.T) {
	release := fixtureRelease("1.2.3", 'a')
	firstRoot := t.TempDir()
	secondRoot := t.TempDir()
	firstResolver := &fakeResolver{latest: release}
	secondResolver := &fakeResolver{latest: release}
	first := Generator{Root: firstRoot, Resolver: firstResolver}
	second := Generator{Root: secondRoot, Resolver: secondResolver}

	firstSnapshot, err := first.Init(context.Background(), configuredFixture())
	if err != nil {
		t.Fatalf("first init: %v", err)
	}
	secondSnapshot, err := second.Init(context.Background(), configuredFixture())
	if err != nil {
		t.Fatalf("second init: %v", err)
	}
	if !reflect.DeepEqual(firstSnapshot.Files, secondSnapshot.Files) {
		t.Fatal("identical inputs generated different bytes")
	}
	before := captureTree(t, firstRoot)
	time.Sleep(10 * time.Millisecond)
	checked, err := first.Check()
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	after := captureTree(t, firstRoot)
	if !reflect.DeepEqual(before, after) {
		t.Fatalf("check modified the repository:\nbefore=%#v\nafter=%#v", before, after)
	}
	if !reflect.DeepEqual(checked.Files, firstSnapshot.Files) {
		t.Fatal("checked canonical bytes differ from generated bytes")
	}
	if _, err := os.Stat(filepath.Join(firstRoot, lockPath)); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("check created transaction state: %v", err)
	}
	if firstResolver.latestCalls != 1 || secondResolver.latestCalls != 1 {
		t.Fatalf("resolver calls = %d/%d, want 1/1", firstResolver.latestCalls, secondResolver.latestCalls)
	}
}

func TestInitRefusesEveryExistingTargetBeforeResolution(t *testing.T) {
	for _, relative := range targetPaths {
		t.Run(strings.ReplaceAll(relative, "/", "_"), func(t *testing.T) {
			root := t.TempDir()
			target := filepath.Join(root, filepath.FromSlash(relative))
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(target, []byte("owner data\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			resolver := &fakeResolver{latest: fixtureRelease("1.2.3", 'a')}
			_, err := (Generator{Root: root, Resolver: resolver}).Init(context.Background(), DefaultConfig())
			assertErrorKind(t, err, ErrorCommittedData)
			if resolver.latestCalls != 0 {
				t.Fatalf("resolver called %d times before refusing existing target", resolver.latestCalls)
			}
		})
	}
}

func TestCheckRejectsDriftWithoutRepair(t *testing.T) {
	testCases := []struct {
		name     string
		relative string
		mutate   func([]byte) []byte
	}{
		{name: "posix script", relative: posixPath, mutate: appendMarker},
		{name: "Windows script", relative: windowsPath, mutate: appendMarker},
		{name: "unknown property", relative: propertiesPath, mutate: appendMarker},
		{
			name: "owner config",
			relative: configPath,
			mutate: func(raw []byte) []byte {
				return bytes.Replace(raw, []byte(`mode = "auto"`), []byte(`mode = "trial"`), 1)
			},
		},
	}
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			root := t.TempDir()
			generator := Generator{Root: root, Resolver: &fakeResolver{latest: fixtureRelease("1.2.3", 'a')}}
			if _, err := generator.Init(context.Background(), configuredFixture()); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(root, filepath.FromSlash(testCase.relative))
			raw, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			mutated := testCase.mutate(raw)
			if err := os.WriteFile(path, mutated, fileModes[testCase.relative]); err != nil {
				t.Fatal(err)
			}
			before := captureTree(t, root)
			_, err = generator.Check()
			assertErrorKind(t, err, ErrorCommittedData)
			if after := captureTree(t, root); !reflect.DeepEqual(before, after) {
				t.Fatal("failed check repaired or otherwise modified drift")
			}
		})
	}
}

func TestUpdatePreservesScriptsAndOwnerConfiguration(t *testing.T) {
	initial := fixtureRelease("1.2.3", 'a')
	next := fixtureRelease("1.3.0", 'b')
	resolver := &fakeResolver{
		latest: initial,
		versions: map[string]Release{
			"1.3.0": next,
		},
	}
	root := t.TempDir()
	generator := Generator{Root: root, Resolver: resolver}
	before, err := generator.Init(context.Background(), configuredFixture())
	if err != nil {
		t.Fatal(err)
	}
	originalTree := captureTree(t, root)
	old, updated, changed, err := generator.Update(context.Background(), "1.3.0", false)
	if err != nil {
		t.Fatalf("update: %v", err)
	}
	if !changed || old.Release.Version != "1.2.3" || updated.Release.Version != "1.3.0" {
		t.Fatalf("unexpected update result: changed=%t old=%s new=%s", changed, old.Release.Version, updated.Release.Version)
	}
	for _, relative := range []string{posixPath, windowsPath, configPath} {
		if !bytes.Equal(before.Files[relative], updated.Files[relative]) {
			t.Fatalf("update changed owner-controlled %s", relative)
		}
	}
	if bytes.Equal(before.Files[propertiesPath], updated.Files[propertiesPath]) {
		t.Fatal("update did not change distribution identity")
	}
	checked, err := generator.Check()
	if err != nil || checked.Release.Version != "1.3.0" {
		t.Fatalf("updated check = %s/%v", checked.Release.Version, err)
	}
	stable := captureTree(t, root)
	_, _, changed, err = generator.Update(context.Background(), "1.3.0", false)
	if err != nil || changed {
		t.Fatalf("same-version update = changed %t/error %v", changed, err)
	}
	if resolver.versionCalls != 1 {
		t.Fatalf("version resolver calls = %d, want 1", resolver.versionCalls)
	}
	if after := captureTree(t, root); !reflect.DeepEqual(stable, after) {
		t.Fatal("same-version update changed files")
	}
	if originalTree[configPath].digest != captureTree(t, root)[configPath].digest {
		t.Fatal("owner configuration digest changed")
	}
}

func TestDowngradeRequiresExplicitAuthority(t *testing.T) {
	initial := fixtureRelease("2.0.0", 'b')
	previous := fixtureRelease("1.9.9", 'a')
	resolver := &fakeResolver{
		latest: initial,
		versions: map[string]Release{
			"1.9.9": previous,
		},
	}
	root := t.TempDir()
	generator := Generator{Root: root, Resolver: resolver}
	if _, err := generator.Init(context.Background(), DefaultConfig()); err != nil {
		t.Fatal(err)
	}
	before := captureTree(t, root)
	_, _, _, err := generator.Update(context.Background(), "1.9.9", false)
	assertErrorKind(t, err, ErrorCommittedData)
	if resolver.versionCalls != 0 || !reflect.DeepEqual(before, captureTree(t, root)) {
		t.Fatal("rejected downgrade resolved metadata or changed files")
	}
	_, after, changed, err := generator.Update(context.Background(), "1.9.9", true)
	if err != nil || !changed || after.Release.Version != "1.9.9" {
		t.Fatalf("authorized downgrade = changed %t/version %s/error %v", changed, after.Release.Version, err)
	}
}

func TestUpdateRejectsDriftBeforeResolution(t *testing.T) {
	resolver := &fakeResolver{
		latest: fixtureRelease("1.2.3", 'a'),
		versions: map[string]Release{
			"1.2.4": fixtureRelease("1.2.4", 'b'),
		},
	}
	root := t.TempDir()
	generator := Generator{Root: root, Resolver: resolver}
	if _, err := generator.Init(context.Background(), DefaultConfig()); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, propertiesPath)
	if err := os.WriteFile(path, appendMarker(mustRead(t, path)), 0o644); err != nil {
		t.Fatal(err)
	}
	_, _, _, err := generator.Update(context.Background(), "1.2.4", false)
	assertErrorKind(t, err, ErrorCommittedData)
	if resolver.versionCalls != 0 {
		t.Fatal("drifted update resolved remote metadata")
	}
}

func TestFailedPublicationRollsBackEveryTarget(t *testing.T) {
	initial := fixtureRelease("1.2.3", 'a')
	next := fixtureRelease("1.2.4", 'b')
	resolver := &fakeResolver{
		latest: initial,
		versions: map[string]Release{
			"1.2.4": next,
		},
	}
	root := t.TempDir()
	generator := Generator{Root: root, Resolver: resolver}
	if _, err := generator.Init(context.Background(), DefaultConfig()); err != nil {
		t.Fatal(err)
	}
	before := captureTree(t, root)
	renameCalls := 0
	failureInjected := false
	generator.rename = func(oldPath, newPath string) error {
		renameCalls++
		if renameCalls == 6 && !failureInjected {
			failureInjected = true
			return errors.New("injected publish failure")
		}
		return os.Rename(oldPath, newPath)
	}
	_, _, _, err := generator.Update(context.Background(), "1.2.4", false)
	assertErrorKind(t, err, ErrorInternal)
	if !failureInjected {
		t.Fatal("publication failure was not injected")
	}
	after := captureTree(t, root)
	if !reflect.DeepEqual(before, after) {
		t.Fatalf("failed publication left partial state:\nbefore=%#v\nafter=%#v", before, after)
	}
	assertNoTransactionResidue(t, root)
}

func TestTransactionLockRejectsConcurrentWriter(t *testing.T) {
	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, lockPath), 0o700); err != nil {
		t.Fatal(err)
	}
	resolver := &fakeResolver{latest: fixtureRelease("1.2.3", 'a')}
	_, err := (Generator{Root: root, Resolver: resolver}).Init(context.Background(), DefaultConfig())
	assertErrorKind(t, err, ErrorInternal)
	if resolver.latestCalls != 1 {
		t.Fatalf("resolver calls = %d, want 1 after preflight", resolver.latestCalls)
	}
	for _, relative := range targetPaths {
		if _, err := os.Lstat(filepath.Join(root, filepath.FromSlash(relative))); !errors.Is(err, fs.ErrNotExist) {
			t.Fatalf("concurrent writer created %s: %v", relative, err)
		}
	}
}

func TestConfigRejectsPartialOrSensitiveInputs(t *testing.T) {
	testCases := []Config{
		{Mode: "auto", ServerURL: "https://buildopt.example.invalid", TrialBudgetPercent: 5},
		{Mode: "auto", ServerURL: "file:///home/alice/state", ProjectScope: "a/b", CredentialEnv: "BUILDOPT_TOKEN", TrialBudgetPercent: 5},
		{Mode: "auto", ServerURL: "https://user:pass@example.invalid", ProjectScope: "a/b", CredentialEnv: "BUILDOPT_TOKEN", TrialBudgetPercent: 5},
		{Mode: "auto", ServerURL: "https://example.invalid/path\"quoted", ProjectScope: "a/b", CredentialEnv: "BUILDOPT_TOKEN", TrialBudgetPercent: 5},
		{Mode: "auto", ServerURL: "https://example.invalid", ProjectScope: "A/B", CredentialEnv: "BUILDOPT_TOKEN", TrialBudgetPercent: 5},
		{Mode: "auto", ServerURL: "https://example.invalid", ProjectScope: "a/b", CredentialEnv: "TOKEN_VALUE", TrialBudgetPercent: 5},
		{Mode: "auto", TrialBudgetPercent: 6},
	}
	for index, config := range testCases {
		if err := validateConfig(config); err == nil {
			t.Fatalf("case %d accepted invalid config: %#v", index, config)
		}
	}
}

type treeEntry struct {
	digest  [32]byte
	mode    fs.FileMode
	modTime time.Time
}

func captureTree(t *testing.T, root string) map[string]treeEntry {
	t.Helper()
	result := make(map[string]treeEntry)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		result[filepath.ToSlash(relative)] = treeEntry{
			digest: sha256.Sum256(raw), mode: info.Mode().Perm(), modTime: info.ModTime(),
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func appendMarker(raw []byte) []byte {
	return append(append([]byte(nil), raw...), []byte("owner drift\n")...)
}

func mustRead(t *testing.T, path string) []byte {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return raw
}

func assertErrorKind(t *testing.T, err error, want ErrorKind) {
	t.Helper()
	var classifiedError *Error
	if !errors.As(err, &classifiedError) || classifiedError.Kind != want {
		t.Fatalf("error = %v, want kind %d", err, want)
	}
}

func assertNoTransactionResidue(t *testing.T, root string) {
	t.Helper()
	var residue []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == root {
			return nil
		}
		name := entry.Name()
		if name == lockPath || strings.HasPrefix(name, ".buildopt-wrapper-") {
			residue = append(residue, path)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(residue)
	if len(residue) != 0 {
		t.Fatalf("transaction residue: %v", residue)
	}
}
